### ISSUE TITLE
Not getting ground in breadboard 

### ISSUE THREAD

**Issue by omeriko9** [Architeuthis-Flux/Jumperless#13] opened 2023-10-28 14:44 UTC
Hey, just got my jumperless and assembled it per instructions, but I can't get GND in any of the breadboard pins except for the ground line.

As you can see, the leds are green signifying Ground, but the led won't turn on:

![image](https://github.com/Architeuthis-Flux/Jumperless/assets/5153984/a0f46889-334d-476a-abde-478e5a6abf79)

This is my Wokwi diagram but I also trying connecting row 1 to the Nano's GND (and many different rows), it still won't work:

![image](https://github.com/Architeuthis-Flux/Jumperless/assets/5153984/1d0eba83-7f09-4486-baf3-3db864650def)

When I connect the led directly to the Ground line (or using a jumper wire) I do get ground.

Any idea how can I fix/debug this?

**Comment by Architeuthis-Flux** [comment] 2023-10-28 15:41
Thanks for putting in this issue! I think I may have left some silly change in the code from debugging something else that isn't connecting Net 0 GND, there's a for loop somewhere starting from 1 instead of 0. I'll find it and put up a fix this morning.

**Comment by Architeuthis-Flux** [comment] 2023-10-28 15:55
Could you also let me know if you have Rev 2 or Rev 3? and if it works on any other rows? The 4 corners of the breadboard (row 1, 30, 31, 60) work slightly differently from the rest, so it's helpful to know whether the issue is just there. On my board, it seems to work elsewhere but not in the corners.

**Comment by omeriko9** [comment] 2023-10-28 17:01
Forgive my ignorance, how can I know which revision the board is? Here is the back of the board:
![image](https://github.com/Architeuthis-Flux/Jumperless/assets/5153984/a92385b9-215e-41e8-a59b-5ea0a378165e)

**Comment by Architeuthis-Flux** [comment] 2023-10-28 17:17
That's on me for not writing the revision number on the boards, you can tell by the location of the ADC (on Rev 3 it's in place of the Nano Disconnect solder jumpers). You have a Revision 2, which is good because that's all I have to test on right now and I found a fix for you. 

Right under the rail supply switch (top right looking at the back) there's a solder jumper that should be cut (if it's not, cut it). Run a jumper from the left side pad to the GND rail. Like this:
![IMG_4669](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/62ec2c22-a008-4e03-9cbc-5239f0631b82)
And you should be able to get GND on the 4 corners. 

I'm working on a more robust fix in firmware that will work on both revisions right now, so when I update the release you should update your firmware. 

<img width="808" alt="Screenshot 2023-10-28 at 10 15 07 AM" src="https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/e8faabd4-b433-455e-b616-460f5d77059b">
The reason for this is the corners are considered a Special Function on Chip L and the pathfinding has to deal with them differently. It's kinda weird but it saved me from having to add another crosspoint switch to the board.

**Comment by Architeuthis-Flux** [comment] 2023-10-28 17:18
Let me know if that works for you.

**Comment by omeriko9** [comment] 2023-10-28 17:36
I will try and let you know, thanks for the elaborate explanation and the care you invest in this issue!

**Comment by Architeuthis-Flux** [comment] 2023-10-28 20:36
Hey, the bug should be fixed in the latest release. Just download firmware.uf2 from the releases page and it should work better. Still do the bodge though, it assumes you've done it. I'll keep hacking away to get it to work without the bodge, so I'll keep this open until that's fully done.

**Comment by omeriko9** [comment] 2023-10-29 08:10
Yes, the patch + latest firmware indeed fixed it, now I get GND on the edge rows. Nice :)

There's another issue where Wokwi + JumperlessWokwiBridge won't update the sketch on the Nano, do you want me to open a different issue for that or are you aware of that already?

**Comment by Architeuthis-Flux** [comment] 2023-10-29 16:10
You can open up an issue for that. But as of now, I haven't written the firmware to do that. It turns out it's pretty complex to grab all the libraries and compile everything into a hex file like that. It's completely feasible, just will take some work in a field of coding I'm not super good with.

For now, the best way to flash code is with a second USB cable, the Jumperless will reset the Arduino each time you change the wiring (I can change it if you don't want it to do that, or just cut the two solder jumpers labeled Reset.)

**Closed** 2023-10-29 16:56 UTC
